### ISSUE TITLE
Make slider pop ups appear below slider

### ISSUE THREAD

**Issue by bkleeman** [rcc-uchicago/sankey#21]
### Problem Statement

- Currently, some of the popups for the slider ticks appear above the slider.
    - This obscures parts of the sankey diagram, and the client wants them all to appear below the slider.

![image](https://user-images.githubusercontent.com/20052075/81424780-18d5d480-911c-11ea-9569-10fd1aaf90c5.png)

### Proposed Solution:

- Find what popper.js property controls the up/down appearance of popups and set it to down only.

### Success Criteria

- Each pop up appears below the slider

**Comment by Milstein** [comment]
I have added a dialog box so user can put it where ever they want!

**Comment by bkleeman** [comment]
Thank you for implementing popper.js without bootstrap! I will close this issue and open a new one to address the further work needed, and I will take it from here.
