### ISSUE TITLE
Format bottom graph tooltip

### ISSUE THREAD

**Issue by bkleeman** [rcc-uchicago/sankey#23]
## Problem Statement
* Currently the bottom graph tooltip displays numbers in scientific notation
* It does not display units
* It all displays on one line
![image](https://user-images.githubusercontent.com/20052075/81434608-0bc0e180-912c-11ea-9f79-42e0f3bfecf9.png)

## Proposed solution
* The client would like the tooltip to display on two lines, formatted something like:

```
2014 - Petroleum:
14.5 MW
```
Or whatever the appropriate units/numbers would be.

## Conversion rates:
* Our base values are in W.
* 1 TW = 10^ 12 W 
* 1 GW = 10^9 W
* 1 MW = 10^6 W
* 1 kW = 10^3 W

**Comment by kreddivari** [comment]
Done!
