### ISSUE TITLE
Set each bottom graph tooltip to the same color

### ISSUE THREAD

**Issue by bkleeman** [rcc-uchicago/sankey#24]
## Problem Statement
* Currently,  each tooltip on the bottom graph is the same color as its corresponding fuel type/graph region:

![image](https://user-images.githubusercontent.com/20052075/81435162-0021ea80-912d-11ea-9fb4-f4f89b7e7dd0.png)
![image](https://user-images.githubusercontent.com/20052075/81435203-116af700-912d-11ea-82ae-5828abbd099d.png)
![image](https://user-images.githubusercontent.com/20052075/81435211-16c84180-912d-11ea-85a9-4fc908f22afa.png)

etc.

## Proposed Solution
* Decide on one single color for each tooltip. 
* Set each tooltip color to that color.

**Comment by kreddivari** [comment]
Please ask Nate to share the common color to fit with all existing color codes..My openion is to keep different colors to identify the category easily...

**Comment by bkleeman** [comment]
Will do thank you! I have reached out to Nate and will close this issue when we have verified the right color.

**Comment by bkleeman** [comment]
Nate says white background works. A light grey outline might be okay. That is an optional enhancement so I will mark this issue closed.
