### ISSUE TITLE
Make slider pop ups appear below slider

### ISSUE THREAD

**Issue by bkleeman** [rcc-uchicago/sankey#31]
### Problem Statement

- Currently, the pop ups for the slider ticks are different than they used to be. See the image below. The client is upset about this because her original specifications were very different. 

![image](https://user-images.githubusercontent.com/20052075/81490230-0905df80-9245-11ea-9b0b-55af581f7d2e.png)

* At present, the popups are actually dialog boxes. They have a grey title bar and require you to click the x button to make them go away. They are draggable. The client wants simple, standard, and boring UI elements by default.

### Proposed Solution:

* Implement a custom pop up from scratch that meets the success criteria below

### Success Criteria

- Pop ups should not be dialog boxes. They should not have an x button to exit. They should be tooltips or similar UI elements that display on click and disappear on a second click anywhere in the document.
- Each individual pop up should have its own fixed position. When possible, the center of the pop up should line up with the tick. When this is not possible, the pop up should snap to whichever side of the slider it is closest to.
- The height of each individual pop up should adjust to match the text.
- Pop ups should appear below the slider regardless of the size of the user's browser window.
- The width of each pop up should be roughly half the width of the slider.
- Please use the following images as a guidline:
![image](https://user-images.githubusercontent.com/20052075/81237339-072de900-8fc5-11ea-801a-e7f2962b92fb.png)

![image](https://user-images.githubusercontent.com/20052075/81237401-2e84b600-8fc5-11ea-99cf-e01ea64b0bb2.png)

![image](https://user-images.githubusercontent.com/20052075/81237501-68ee5300-8fc5-11ea-920a-ded73b3419ce.png)

![image](https://user-images.githubusercontent.com/20052075/81237546-87544e80-8fc5-11ea-9bbe-ba1499b75a69.png)

![image](https://user-images.githubusercontent.com/20052075/81237604-af43b200-8fc5-11ea-8cd7-7a623578ed15.png)
 
Below is a good example for visual reference.
![image](https://user-images.githubusercontent.com/20052075/81489824-e9b88380-923f-11ea-8894-8879519aa929.png)

**Comment by bkleeman** [comment]
Success criteria edited for clarity

**Comment by bkleeman** [comment]
Issue edited to reflect current status, 05/09 10:50 pm

**Comment by Milstein** [comment]
I believe the latest version is far better : still if you want to refine and use your math skills you can try to modify this file : https://github.com/rcc-uchicago/sankey/commit/9be71a4f51171c1a71c4a48065985c496de31e0a
