### ISSUE TITLE
Adjust styles for popup w/ significant year info

### ISSUE THREAD

**Issue by bkleeman** [rcc-uchicago/sankey#9]
### Problem Statement

- Currently, the popups that appear below the slider are too wide.
    - Right now they extend left and right far past all the other core elements on the page (chart, slider, header, graphs, etc).

![image](https://user-images.githubusercontent.com/20052075/81341678-8e3b9980-9077-11ea-8513-f3b70d0af4f9.png)

### Proposed Solution

- The width of each of these popups should be some fraction of the width of the slider.
- When possible, the center of the pop up should line up with the tick.
    - When this is not possible, the pop up should start from whichever side of the slider it is closest to.
- The popups should look something more like the following:
![image](https://user-images.githubusercontent.com/20052075/81237339-072de900-8fc5-11ea-801a-e7f2962b92fb.png)

![image](https://user-images.githubusercontent.com/20052075/81237401-2e84b600-8fc5-11ea-99cf-e01ea64b0bb2.png)

![image](https://user-images.githubusercontent.com/20052075/81237501-68ee5300-8fc5-11ea-920a-ded73b3419ce.png)

![image](https://user-images.githubusercontent.com/20052075/81237546-87544e80-8fc5-11ea-9bbe-ba1499b75a69.png)

![image](https://user-images.githubusercontent.com/20052075/81237604-af43b200-8fc5-11ea-8cd7-7a623578ed15.png)

The pop ups can be wider than they are illustrated above, but should not be the full width of the slider.

**Comment by Milstein** [comment]
I have used now Popper https://getbootstrap.com/docs/4.1/components/popovers/ this might be a good solution for now. Let me know yours thought.

**Comment by bkleeman** [comment]
This is excellent progress, thank you Milson! I will open separate issues for the remaining problems as discussed in our meeting.
